config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :shots, only: [:new, :create, :index, :show, :destroy]
  end

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :shots, dependent: :delete_all
  has_many :roles, dependent: :delete_all
  validates :name, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/shot.rb
class Shot < ActiveRecord::Base
  validates :name, presence: true
  validates :image, presence: true
  belongs_to :project
  belongs_to :owner, class_name: 'User'

  has_attached_file :image,
                    :styles => {
                        :thumb => '200x150#'
                    }
  validates_attachment :image, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :unarchived, -> { where(archived_at: nil) }

  def to_s
    "#{email} [#{admin? ? 'Admin' : 'User'}]"
  end

  def archive
    update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && self.archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

  before_action :ensure_admin!

  def index
  end

  private

  def ensure_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: 'Only admins allowed in there <3'
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project Created"
    else
      flash.now[:alert] = "Project not Created"
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path, notice: "Project Deleted."
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.unarchived.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: 'From the mighty fires you have forged a new user.'
    else
      flash.now[:alert] = "User not Created"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User Updated'
    else
      flash.now[:alert] = 'User not Updated'
      render :edit
    end
  end

  def archive
    @user = User.find(params[:id])
    if @user == current_user
      flash[:alert] = 'Cannot archive yourself'
    else
      @user.archive
      flash[:notice] = 'User has been archived'
    end

    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  protect_from_forgery with: :exception

  private

  def not_authorized
    redirect_to root_path, alert: 'You are not allowed here. Try logging in if you haven\'t already.'
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = find_project
    authorize @project, :show?
  end

  def index
    @projects = Project.all
  end

  def edit
    @project = find_project
  end

  def update
    @project = find_project
    if @project.update(project_params)
      redirect_to @project, notice: "Project Updated."
    else
      flash.now[:alert] = "Project not Updated."
      render :edit
    end
  end

  private

  def find_project
    Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to projects_path, alert: "The project you were looking for doesn't exist"
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  def new
    @project = find_project
    @shot = @project.shots.build
  end

  def create
    @project = find_project
    @shot = @project.shots.build(shot_params)
    @shot.owner = current_user

    if @shot.save
      redirect_to [@project, @shot], notice: "Shot Created."
    else
      flash.now[:alert] = "Shot not created."
      render :new
    end
  end

  def show
    @project = find_project
    @shot = @project.shots.find(params[:id])
  end

  def index
    @project = find_project
    @shots = @project.shots
  end

  def destroy
    @project = find_project
    @shot = @project.shots.find(params[:id])
    @shot.destroy
    redirect_to @project, notice: "Shot deleted."
  end

  private

  def find_project
    Project.find(params[:project_id])
  end

  def shot_params
    params.require(:shot).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/admin/application/index.html.erb
<h1>Admin Area</h1>

<ul>
  <li><%= link_to 'Users', admin_users_path %></li>
</ul>

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, project]) do |f| %>
  <%= f.input "name" %>
  <%= f.input "description" %>
  <%= f.submit %>
<% end %>

app/views/admin/projects/new.html.erb
<h1>Projects Home</h1>

<%= render "form", project: @project %>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :admin, label: 'Is an admin?' %>

  <%= f.button :submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_admin_user_path %>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<h1><%= @user %></h1>

<%= link_to 'Edit User', edit_admin_user_path(@user) %>
<%= link_to 'Archive User', archive_admin_user_path(@user), method: :patch,
data: { confirm: 'Are you sure you want to archive this user?' } %>

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_header.html.erb
<!-- Header -->
<header>
  <div id="logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.svg" %>
    <% end %>
  </div>
  <div id="hamburger-menu"><a href="#"></a></div>
</header>

<!-- Mobile Nav -->
<nav id="mobile-nav">
  <ul>
    <% admins_only do %>
      <li><%= link_to 'Admin', admin_root_path %></li>
    <% end %>
    <% if user_signed_in? %>
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "header" %>
  <%= render "flashes" -%>

  <div class="container">
    <%= yield %>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for project do |f| %>
  <%= f.input "name" %>
  <%= f.input "description" %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% admins_only do %>
  <%= link_to 'New Project', new_admin_project_path %>
<% end %>

<% @projects.each do |project| %>
  <h2><%= link_to project.name, project %></h2>
  <p><%= project.description %></p>
  <hr/>
<% end %>

app/views/projects/new.html.erb
<h1>Projects Home</h1>

<%= simple_form_for @project do |f| %>
  <%= f.input "name" %>
  <%= f.input "description" %>
  <%= f.submit "Create Project" %>
<% end %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<p><%= @project.description %></p>

<%= link_to 'Edit Project', edit_project_path(@project) %><br>
<% admins_only do %>
  <%= link_to 'Delete Project',
              admin_project_path(@project),
              method: :delete,
              data: {confirm: 'Are you sure you want to delete this project?'}
  %>
<% end %>

<hr>

<section>
  <h2>Shots</h2>

  <ul class="actions">
    <li><%= link_to "New Shot", new_project_shot_path(@project) %></li>
  </ul>

  <ul class="project--shots">
    <% @project.shots.each do |shot| %>
      <%= link_to [@project, shot] do %>
        <li>
          <div><%= image_tag shot.image.url(:thumb) %></div>
          <div class="description">
            <h4>
              <%= shot.name %>
            </h4>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>

</section>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/shots/_form.html.erb
<%= simple_form_for([project, shot]) do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>

  <%= f.button :submit %>
<% end %>

app/views/shots/index.html.erb
<h1><%= @project.name %> Shots</h1>

<div class="cards">
  <% @project.shots.each do |shot| %>
    <div class="card">
      <%= link_to [@project, shot] do %>
        <div class="card-image">
          <%= image_tag shot.image.url %>
        </div>
        <div class="card-header">
          <%= shot.name %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shots/new.html.erb
<section class="header-with-subtitle">
  <h1>New Shot</h1>
  <span><%= @project.name %></span>
</section>

<%= render "form", project: @project, shot: @shot %>

app/views/shots/show.html.erb
<h1>Shot Details</h1>

<h2><%= @shot.name %></h2>
<p>Create <%= time_ago_in_words(@shot.created_at) %> ago by <%= @shot.owner.email %></p>
<%= image_tag @shot.image.url %>

<%= link_to "Delete Shot", project_shot_path(@project, @shot), method: :delete %>